### ISSUE TITLE
Create several reports - MAIN

### ISSUE THREAD

**Issue by slsevilla** [ODHL/AST_Workflow#6]
Main page to track new report generation
- [x] Updates to base report (https://github.com/ODHL/AST_Workflow/issues/7)
- [x] An outbreak report (https://github.com/ODHL/AST_Workflow/issues/8)
- [ ] A novel organism report (https://github.com/ODHL/AST_Workflow/issues/9)
- [ ] A regional report (https://github.com/ODHL/AST_Workflow/issues/10)
- [ ] A time-based report (https://github.com/ODHL/AST_Workflow/issues/11)

**Comment by slsevilla** [comment]
## Workflow
### Trigger: New project
- Run ODHL AST Pipeline
- Generate base report
- Move intermediate data to L drive from AWS

### Trigger: Outbreak Report
- Receive manifest of projectID's and sample names
- Move intermediate data from L drive to AWS
- Generate Outbreak report

### Trigger: Novel Organism
- Receive projectID and sample name
- Move intermediate data from L drive to AWS
- Generate Novel Organism report

### Trigger: Regional Report
- Receive manifest of projectID's, sample names, locations
- Move intermediate data from L drive to AWS
- Generate Regional report

### Trigger: Time Report
- Receive manifest of projectID's, sample names, time
- Move intermediate data from L drive to AWS
- Generate Time report

**Comment by slsevilla** [comment]
completed the necessary reports
